name: Build and push images
on:
  push:
    branches:
    - master
    paths:
    - '*'
    - '!README.md'
  schedule:
    # As well as running when we make changes we should run at least
    # every week in order to pick up new parent images and new versions of Snyk
    - cron:  "0 0 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to registry
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run:
        docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
    - name: Build all images
      env:
        DOCKER_BUILDKIT: "1"
      run:
        make
    - name: Run tests
      run:
        make test
    - name: Push images
      run:
        make push


