name: Build and push images
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    # Actions doesn't currently have access to push to Package Registry
    # https://github.community/t5/GitHub-Actions/Github-Actions-Docker-login/td-p/29852
    - name: Login to GitHub Package Registry
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run:
        docker login docker.pkg.github.com --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
    - name: Build all images
      env:
        DOCKER_BUILDKIT: "1"
      run:
        make
    - name: Run tests
      run:
        make test
    - name: Push images
      run:
        make push


