name: Build and push images
on:
  push:
    branches:
    - master
    paths:
    - '*'
    - '!README.md'
  schedule:
    # As well as running when we make changes we should run at least
    # every week in order to pick up new parent images and new versions of Snyk
    - cron:  "0 0 * * 0"


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - base: node
            tag: node
          - base: node:10
            tag: node-10
    steps:
    - uses: actions/checkout@v1
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        add_git_labels: true
        repository: snyk/snyk
        tags: ${{ matrix.tag }}
        build_args: IMAGE=${{ matrix.base }}


