name: "Generate Actions to build Snyk images"
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - build.rb
      - linux
      - alpine

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: Render latest template
        run: |
          ruby build.rb
      - uses: seanmiddleditch/gha-publish-to-git@master
        with:
          branch: master
          github_token: ${{ secrets.workflow_token }}
          github_pat: ${{ secrets.workflow_token }}
          commit_author: "gareth@morethanseven.net"
          commit_message: Generated new Action to build Snyk images
